### PR TITLE
Add unique span IDs, and base span equality on them

### PR DESCRIPTION
**Pull request by hawkw**
This branch introduces a `span::Id` type and changes span equality to be
based on the span's `Id`. The `Id` type is used to identify the span within
the context of the process.

These span IDs are intended to be used as a source of truth for
determining whether two span handles are equal. Previously, this
was done based on the span's creation timestamp and metadata, but the
creation timestamps are slated for removal (see #24). When they are
removed, the metadata alone will not be sufficient to uniquely identify
the span, since that would mean two distinct spans created at the same
call site would be "equal". 

Similarly, we cannot base span equality on their field values, for a
number of reasons: 
+ Two spans with the same metadata and no fields would be equal,
  even if they are distinct periods of time. 
+ Similarly, two spans which happen to have the same field values, but
  represent distinct periods of time would also be incorrectly equal. 
+ Using field values for equality and hashing would require that
 `Value`s implement `Hash` and `PartialEq`, which they cannot do when
  they are represented by trait objects (as these traits are not object 
  safe). 
+ Also, comparing the field values would require iterating across all
  the fields.

Currently, the `Id` type is represented by a `u64`. However, the `Id`
type is opaque to downstream users, beyond the contract of implementing
`Clone`, `Hash`, and `PartialEq`, and being able to be _constructed_
from a `u64`, so we could swap out this implementation with something
else later fairly transparently, as long as we can construct it from a
`u64`.

`Subscriber`s are responsible for generating the IDs for each span
(through the `Subscriber::new_span_id` trait method), allowing them to
choose the span ID generation strategy that supports their use case.

Required for #24

### CODE REVIEW

**Comment by carllerche** [comment]
I would rather avoid using a static counter to reference the span ID, especially given that there is the chance of wrap around (on 32bit systems).

I'm also unclear on how the subscriber is supposed to use it.

Is there an example of a subscriber that builds up the tree structure in memory? As in, the subscriber can walk the tree from the root to all the spans?

**Comment by hawkw** [comment]
@carllerche 
> I would rather avoid using a static counter to reference the span ID, especially given that there is the chance of wrap around (on 32bit systems).

Yeah, I was concerned about that as well; if `AtomicU64` was stable I would have used one. This was largely intended as a placeholder implementation, and I thought the span ID type was opaque enough that it could be swapped out with a more robust internal implementation. 

With that said, do you have any suggestions for more robust ways to generate process-unique identifiers? I didn't want to use a random number generator, because that could require a syscall, and has the potential of producing collisions, so I thought an increasing counter seemed like a better approach. 

> I'm also unclear on how the subscriber is supposed to use it.

Currently, it's really only intended to be used for span equality and for generating hashes so span data can be stored in hashmaps and similar structures. 

> Is there an example of a subscriber that builds up the tree structure in memory? As in, the subscriber can walk the tree from the root to all the spans?

Not currently, but I can certainly write one. The `sloggish` example has a subscriber that holds the hashes of the _current branch_ of the tree in memory for determining indentation levels. However, that code is also not particularly _good_ --- it was written as a quick sketch early on in the prototyping process, and can probably be improved significantly...

**Comment by carllerche** [comment]
I think it would be worth enumerating the kind of subscribers we would expect.

It’s very possible that actually reconstructing the tree structure in the subscriber is not important.

**Comment by carllerche** [comment]
Either way, it does not look like this logic should live in "core" (#23).

IMO, the logic of generating the span IDs should be pushed into the subscriber and stay out of "core". This will allow easier iteration w/o breaking the core API.

**Comment by hawkw** [comment]
@carllerche 
> IMO, the logic of generating the span IDs should be pushed into the subscriber and stay out of "core". This will allow easier iteration w/o breaking the core API.

I'm open to that, but I've also been trying to avoid adding too many required methods to the `Subscriber` trait. 

I agree that generating span IDs ought not be in `tokio-trace-core`, and users should be able to plug in their own span ID generation strategy, but IMHO that concern seems potentially orthogonal  to the `Subscriber` trait. If the purpose of span IDs is primarily for equality and as hash keys, it seems like a `Subscriber` doesn't care what they are as long as they're `Hash + Eq`. 

Also, I'm not immediately sure how to reconcile generating span IDs from a subscriber trait method in situations where spans are fanned out to multiple subscribers. I'd rather not give every span a typemap of subscriber type to that subscriber's ID, for example.

Perhaps there ought to be another trait for something that generates span IDs, so that it's composable with subscriber implementations?

**Comment by hawkw** [comment]
Also, I've written an example of what a subscriber that constructs in-memory span trees might look like, if you're still interested: https://github.com/hawkw/tokio-trace-prototype/compare/eliza/roots-example?expand=1

**Comment by carllerche** [comment]
@hawkw it sounds like you are assuming that the "fanout" subscriber strategy would be handled by every destination subscriber implementing the same trait as the root subscriber, that is not how I see it.

Given that the core API only allows one subscriber, it is perfectly fine IMO to have the core API provide an "advanced" subscriber trait, then have a separate crate (e.g. tokio-trace-subscribers) provide its own `Subscriber` trait that it uses to fan out.

> it seems like a Subscriber doesn't care what they are as long as they're Hash + Eq.

I have the opposite feeling. It may be that a subscriber doesn't care at all about span IDs and is only monitoring time spent in a single call site.. in which case any additional work done to support `Hash + Eq` is wasted.

Subscribers will have wildly different logic. It seems fair to allow them to track spans in a way most appropriate to their needs.

**Comment by carllerche** [comment]
It also seems to me that, as the various strategies for generating IDs are explored, there is no perfect solution. Each strategy has pros and cons depending on what the subscriber intends to do. This indicates to me that the subscriber should be responsible for generating IDs.

**Comment by hawkw** [comment]
@carllerche 
> it sounds like you are assuming that the "fanout" subscriber strategy would be handled by every destination subscriber implementing the same trait as the root subscriber, that is not how I see it.

That's fair; I thought that an API where any arbitrary subscriber can be installed as the root subscriber (and whether fans out or not is an implementation detail) seemed more elegant, but your suggestions here make sense. I'm on board with making subscribers responsible for ID generation.

That said, I think it's important that IDs be of a uniform type (perhaps `u64`?) --- otherwise, spans would either have to be generic over their ID type, which doesn't play nice with the thread local `CURRENT_SPAN`, or they would have to be boxed trait objects, which I'd prefer to avoid...

**Comment by carllerche** [comment]
> That's fair; I thought that an API where any arbitrary subscriber can be installed as the root subscriber (and whether fans out or not is an implementation detail) seemed more elegant

Subscribers generating IDs should not preclude this?

> That said, I think it's important that IDs be of a uniform type (perhaps `u64`?)

I'd start w/ an internal rep of `u64`, but new type it and have `SpanId::from_u64(...)` as the constructor.

**Comment by hawkw** [comment]
@carllerche 

> I'd start w/ an internal rep of u64, but new type it and have `SpanId::from_u64(...)` as the constructor.

Yeah, that's what I'm doing 😄

**Comment by hawkw** [comment]
@carllerche what do you think of 2fe9091954641d1027e1e68b7599364158e6bf42?

**Comment by carllerche** [comment]
Seems like a good step. I would probably call it `new_span` or something like that since odds are, internally, the subscriber is storing span state.

**Comment by hawkw** [comment]
@carllerche I think renaming the function to `new_span` is probably a good step, but I think if we're going to do that, the semantics would need to change somewhat. At the very least, the function should have access to more of the span's data, and not just its metadata.

I've sketched out that change in [this branch](https://github.com/hawkw/tokio-trace-prototype/compare/eliza/simple-span-id...eliza/new-span?expand=1), but I think it might require additional changes as well...

**Comment by carllerche** [comment]
Maybe call it `Attributes` or something. I wouldn't worry too much about the name at this point. We can bikeshed that once the structure is good.

**Comment by hawkw** [comment]
@carllerche I've merged the `new_span_id` -> `new_span` change into this branch, and I'd like to merge this now, unless you have any other concerns? 

Thanks for discussing this with me in such depth --- I think most of the additional considerations can be addressed as we make other changes.

**Pull request merged**
